### ISSUE TITLE
Removing the P icon on the title

### ISSUE THREAD

**Issue by dmccrevan** [biomadeira/sustain#7]
Where would the code be to change the icon on the title, or to just remove it?

**Comment by biomadeira** [comment]
Sorry @dmccrevan

I am not sure what are you referring to... Do you mean the favicon?

**Comment by dmccrevan** [comment]
Yes, I have my own facivon in static/img/ but for some reason the one that you had default is still appearing.

**Comment by biomadeira** [comment]
Hi @dmccrevan 

The line you need to edit or remove is this https://github.com/biomadeira/sustain/blob/gh-pages/_layouts/layout.html#L9
Since you got a favicon of yours, the problem is just that your browser has cached the previous one... I guess you can try reload the page a few times as well as trying it on a different browser...

For chrome check https://productforums.google.com/forum/#!topic/chrome/zXlEW0ZFErY

**Comment by dmccrevan** [comment]
I guess it was the cache issue...Clear cache extension for chrome didn't clear it i guess lol, thanks though! Really like sustain & vitae

**Comment by biomadeira** [comment]
Thanks @dmccrevan ;)
